export interface Tool {
  id: string;
  name: string;
  description: string;
  category: string;
  icon: string;
  path: string;
  tags?: string[];
  isNew?: boolean;
}

export interface Category {
  id: string;
  name: string;
  description: string;
  icon: string;
}

export const categories: Category[] = [
  {
    id: 'developer',
    name: 'Developer Tools',
    description: 'Tools for developers and programmers',
    icon: 'Code2',
  },
  {
    id: 'text',
    name: 'Text Tools',
    description: 'Text manipulation and formatting',
    icon: 'FileText',
  },
  {
    id: 'converter',
    name: 'Converters',
    description: 'Convert between different formats',
    icon: 'RefreshCw',
  },
  {
    id: 'math',
    name: 'Math',
    description: 'Calculations and math utilities',
    icon: 'Calculator',
  },
  {
    id: 'image',
    name: 'Image Tools',
    description: 'Image manipulation and processing',
    icon: 'Image',
  },
  {
    id: 'color',
    name: 'Color Tools',
    description: 'Color manipulation and conversion',
    icon: 'Palette',
  },
  {
    id: 'generator',
    name: 'Generators',
    description: 'Generate various content',
    icon: 'Sparkles',
  },
  {
    id: 'security',
    name: 'Security',
    description: 'Security and encryption tools',
    icon: 'ShieldCheck',
  },
];

export const tools: Tool[] = [
  // Developer Tools
  {
    id: 'modern-color',
    name: 'Modern Color Converter',
    description: 'Convert between HEX, RGB, HSL, OKLCH, LAB, and LCH',
    category: 'color',
    icon: 'Pipette',
    path: '/tools/modern-color',
    tags: ['color', 'hex', 'rgb', 'hsl', 'oklch', 'lab', 'lch'],
    isNew: true,
  },
  {
    id: 'media-query',
    name: 'Media Query Generator',
    description: 'Generate responsive CSS breakpoints',
    category: 'developer',
    icon: 'Monitor',
    path: '/tools/media-query',
    tags: ['css', 'media', 'query', 'responsive', 'breakpoint'],
    isNew: true,
  },
  {
    id: 'data-uri',
    name: 'Data URI Maker',
    description: 'Convert files to Base64 Data URIs for CSS',
    category: 'developer',
    icon: 'FileCode',
    path: '/tools/data-uri',
    tags: ['data', 'uri', 'base64', 'css', 'embed'],
    isNew: true,
  },
  {
    id: 'barcode-studio',
    name: 'Barcode Studio',
    description: 'Generate Code128, EAN, UPC barcodes',
    category: 'generator',
    icon: 'Barcode',
    path: '/tools/barcode-studio',
    tags: ['barcode', 'ean', 'upc', 'code128', 'retail'],
    isNew: true,
  },
  {
    id: 'web-vitals',
    name: 'Web Vitals Simulator',
    description: 'Estimate Core Web Vitals scores',
    category: 'developer',
    icon: 'Gauge',
    path: '/tools/web-vitals',
    tags: ['web', 'vitals', 'lcp', 'fid', 'cls', 'performance'],
    isNew: true,
  },
  {
    id: 'json-sql-schema',
    name: 'JSON to SQL Schema',
    description: 'Inferred SQL table definitions from JSON',
    category: 'developer',
    icon: 'Database',
    path: '/tools/json-sql-schema',
    tags: ['json', 'sql', 'schema', 'database'],
    isNew: true,
  },
  {
    id: 'datetime-hub',
    name: 'DateTime Hub',
    description: 'Advanced timezone and date calculator',
    category: 'math',
    icon: 'Clock',
    path: '/tools/datetime-hub',
    tags: ['date', 'time', 'timezone', 'calculator'],
    isNew: true,
  },
  {
    id: 'js-logger',
    name: 'JS Console Prettifier',
    description: 'Visual debugger for complex JS objects',
    category: 'developer',
    icon: 'Bug',
    path: '/tools/js-logger',
    tags: ['js', 'console', 'debug', 'log'],
    isNew: true,
  },
  {
    id: 'og-debugger',
    name: 'Open Graph Debugger',
    description: 'Social media link preview simulator',
    category: 'developer',
    icon: 'Share2',
    path: '/tools/og-debugger',
    tags: ['og', 'seo', 'social', 'preview'],
    isNew: true,
  },
  {
    id: 'html-markdown',
    name: 'HTML to Markdown',
    description: 'Convert HTML code to Markdown syntax',
    category: 'text',
    icon: 'FileText',
    path: '/tools/html-markdown',
    tags: ['html', 'markdown', 'convert', 'content'],
    isNew: true,
  },
  {
    id: 'jwt-generator',
    name: 'JWT Generator',
    description: 'Generate signed JSON Web Tokens',
    category: 'security',
    icon: 'Fingerprint',
    path: '/tools/jwt-generator',
    tags: ['jwt', 'token', 'auth', 'generate'],
    isNew: true,
  },
  {
    id: 'gql-json',
    name: 'GraphQL to JSON',
    description: 'Generate mock JSON from GQL queries',
    category: 'developer',
    icon: 'Code2',
    path: '/tools/gql-json',
    tags: ['graphql', 'json', 'mock', 'api'],
    isNew: true,
  },
  {
    id: 'mime-types',
    name: 'MIME Types',
    description: 'Lookup MIME types and file extensions',
    category: 'developer',
    icon: 'FileCode',
    path: '/tools/mime-types',
    tags: ['mime', 'file', 'type', 'extension'],
    isNew: true,
  },
  {
    id: 'stopwatch',
    name: 'Stopwatch',
    description: 'Millisecond timer with lap tracking',
    category: 'math',
    icon: 'Timer',
    path: '/tools/stopwatch',
    tags: ['timer', 'stopwatch', 'chronometer', 'time'],
    isNew: true,
  },
  {
    id: 'numeronym',
    name: 'Numeronym Generator',
    description: 'Generate abbreviations like a11y, i18n',
    category: 'text',
    icon: 'Hash',
    path: '/tools/numeronym',
    tags: ['numeronym', 'abbreviation', 'a11y', 'i18n'],
    isNew: true,
  },
  {
    id: 'nato-alphabet',
    name: 'Text to NATO',
    description: 'Convert text to NATO phonetic alphabet',
    category: 'text',
    icon: 'Globe',
    path: '/tools/nato-alphabet',
    tags: ['nato', 'phonetic', 'alphabet', 'spell'],
    isNew: true,
  },
  {
    id: 'iban-validator',
    name: 'IBAN Validator',
    description: 'Validate and parse IBAN numbers',
    category: 'converter',
    icon: 'Landmark',
    path: '/tools/iban-validator',
    tags: ['iban', 'bank', 'validate', 'transfer'],
    isNew: true,
  },
  {
    id: 'camera-recorder',
    name: 'Camera Recorder',
    description: 'Record video from camera or screen',
    category: 'image',
    icon: 'Camera',
    path: '/tools/camera-recorder',
    tags: ['video', 'record', 'camera', 'screen'],
    isNew: true,
  },
  {
    id: 'emoji-picker',
    name: 'Emoji Picker',
    description: 'Browse and copy emojis easily',
    category: 'generator',
    icon: 'Smile',
    path: '/tools/emoji-picker',
    tags: ['emoji', 'smile', 'copy', 'social'],
    isNew: true,
  },
  {
    id: 'ipv6-ula',
    name: 'IPv6 ULA Generator',
    description: 'Generate unique local IPv6 prefixes',
    category: 'developer',
    icon: 'Globe',
    path: '/tools/ipv6-ula',
    tags: ['ipv6', 'ula', 'network', 'rfc4193'],
    isNew: true,
  },
  {
    id: 'wysiwyg-editor',
    name: 'WYSIWYG Editor',
    description: 'Visual HTML editor with live source',
    category: 'developer',
    icon: 'FileCode',
    path: '/tools/wysiwyg-editor',
    tags: ['html', 'editor', 'wysiwyg', 'web'],
    isNew: true,
  },
  {
    id: 'phone-parser',
    name: 'Phone Parser',
    description: 'Validate and format phone numbers',
    category: 'text',
    icon: 'Phone',
    path: '/tools/phone-parser',
    tags: ['phone', 'format', 'validate', 'mobile'],
    isNew: true,
  },
  {
    id: 'mac-address',
    name: 'MAC Address Tool',
    description: 'Generate and lookup MAC addresses',
    category: 'developer',
    icon: 'Monitor',
    path: '/tools/mac-address',
    tags: ['mac', 'address', 'oui', 'vendor'],
    isNew: true,
  },
  {
    id: 'port-generator',
    name: 'Random Port Generator',
    description: 'Generate random non-conflicting ports',
    category: 'developer',
    icon: 'Server',
    path: '/tools/port-generator',
    tags: ['port', 'tcp', 'udp', 'network'],
    isNew: true,
  },
  {
    id: 'ip-range-expander',
    name: 'IP Range Expander',
    description: 'Expand CIDR and IP ranges to lists',
    category: 'developer',
    icon: 'Maximize2',
    path: '/tools/ip-range-expander',
    tags: ['ip', 'range', 'cidr', 'expand'],
    isNew: true,
  },
  {
    id: 'svg-optimizer',
    name: 'SVG Optimizer',
    description: 'Minify and optimize SVG vector files',
    category: 'image',
    icon: 'Minimize2',
    path: '/tools/svg-optimizer',
    tags: ['svg', 'minify', 'optimize', 'vector'],
    isNew: true,
  },
  {
    id: 'base64-image-to-file',
    name: 'Base64 to Image',
    description: 'Convert Base64 back to image files',
    category: 'converter',
    icon: 'FileImage',
    path: '/tools/base64-image-to-file',
    tags: ['base64', 'image', 'convert', 'decode'],
    isNew: true,
  },
  {
    id: 'text-compressor',
    name: 'Text Compressor',
    description: 'Test Gzip and Zlib text compression',
    category: 'developer',
    icon: 'Gauge',
    path: '/tools/text-compressor',
    tags: ['compress', 'gzip', 'zlib', 'size'],
    isNew: true,
  },
  {
    id: 'pdf-integrity',
    name: 'PDF Integrity Check',
    description: 'Verify PDF signatures and metadata',
    category: 'security',
    icon: 'FileSignature',
    path: '/tools/pdf-integrity',
    tags: ['pdf', 'signature', 'security', 'metadata'],
    isNew: true,
  },
  {
    id: 'sql-json',
    name: 'SQL to JSON',
    description: 'Convert SQL INSERT to JSON array',
    category: 'developer',
    icon: 'Database',
    path: '/tools/sql-json',
    tags: ['sql', 'json', 'convert', 'data'],
    isNew: true,
  },
  {
    id: 'curl-converter',
    name: 'Curl to Code',
    description: 'Convert curl commands to JS, Python, Go',
    category: 'developer',
    icon: 'Terminal',
    path: '/tools/curl-converter',
    tags: ['curl', 'fetch', 'api', 'convert'],
    isNew: true,
  },
  {
    id: 'json-sql',
    name: 'JSON to SQL',
    description: 'Generate SQL INSERT from JSON data',
    category: 'developer',
    icon: 'FileJson',
    path: '/tools/json-sql',
    tags: ['json', 'sql', 'convert', 'insert'],
    isNew: true,
  },
  {
    id: 'ssl-decoder',
    name: 'SSL Decoder',
    description: 'Decode and inspect X.509 certificates',
    category: 'security',
    icon: 'Lock',
    path: '/tools/ssl-decoder',
    tags: ['ssl', 'cert', 'x509', 'security'],
    isNew: true,
  },
  {
    id: 'readability-analyzer',
    name: 'Readability Analyzer',
    description: 'Analyze text difficulty and grading',
    category: 'text',
    icon: 'BookOpen',
    path: '/tools/readability-analyzer',
    tags: ['text', 'readability', 'grading', 'flesch'],
    isNew: true,
  },
  {
    id: 'css-grid',
    name: 'CSS Grid Generator',
    description: 'Design complex grid layouts visually',
    category: 'image',
    icon: 'LayoutGrid',
    path: '/tools/css-grid',
    tags: ['css', 'grid', 'layout', 'design'],
    isNew: true,
  },
  {
    id: 'css-flexbox',
    name: 'CSS Flexbox Generator',
    description: 'Build flexible flexbox containers visually',
    category: 'image',
    icon: 'Layout',
    path: '/tools/css-flexbox',
    tags: ['css', 'flexbox', 'layout', 'design'],
    isNew: true,
  },
  {
    id: 'contrast-checker',
    name: 'Contrast Checker',
    description: 'Check WCAG color contrast accessibility',
    category: 'image',
    icon: 'Palette',
    path: '/tools/contrast-checker',
    tags: ['accessibility', 'color', 'contrast', 'wcag'],
    isNew: true,
  },
  {
    id: 'json5-converter',
    name: 'JSON5 to JSON',
    description: 'Convert JSON5 to standard JSON',
    category: 'developer',
    icon: 'Braces',
    path: '/tools/json5-converter',
    tags: ['json', 'json5', 'convert', 'strict'],
    isNew: true,
  },
  {
    id: 'aspect-ratio',
    name: 'Aspect Ratio Calculator',
    description: 'Calculate and preview aspect ratios',
    category: 'image',
    icon: 'Maximize2',
    path: '/tools/aspect-ratio',
    tags: ['design', 'image', 'aspect', 'ratio'],
    isNew: true,
  },
  {
    id: 'color-palette',
    name: 'Color Palette Extractor',
    description: 'Extract color schemes from any image',
    category: 'image',
    icon: 'Palette',
    path: '/tools/color-palette',
    tags: ['color', 'palette', 'image', 'extract'],
    isNew: true,
  },
  {
    id: 'lottie-preview',
    name: 'Lottie Previewer',
    description: 'Test and inspect Lottie JSON animations',
    category: 'image',
    icon: 'Play',
    path: '/tools/lottie-preview',
    tags: ['lottie', 'animation', 'json', 'visual'],
    isNew: true,
  },
  {
    id: 'json-go',
    name: 'JSON to Go Struct',
    description: 'Convert JSON to Go data structures',
    category: 'developer',
    icon: 'Code2',
    path: '/tools/json-go',
    tags: ['json', 'go', 'golang', 'struct'],
    isNew: true,
  },
  {
    id: 'performance-benchmark',
    name: 'Performance Benchmark',
    description: 'Compare JS code snippet speeds',
    category: 'developer',
    icon: 'Activity',
    path: '/tools/performance-benchmark',
    tags: ['benchmark', 'performance', 'js', 'speed'],
    isNew: true,
  },
  {
    id: 'cron-validator',
    name: 'Cron Validator',
    description: 'Verify and test cron expressions',
    category: 'developer',
    icon: 'ShieldCheck',
    path: '/tools/cron-validator',
    tags: ['cron', 'validate', 'schedule', 'test'],
    isNew: true,
  },
  {
    id: 'svg-path',
    name: 'SVG Path Visualizer',
    description: 'Visual playground for SVG path data',
    category: 'image',
    icon: 'PenTool',
    path: '/tools/svg-path',
    tags: ['svg', 'path', 'draw', 'vector'],
    isNew: true,
  },
  {
    id: 'box-shadow',
    name: 'Box Shadow Studio',
    description: 'Design modern multi-layered CSS shadows',
    category: 'image',
    icon: 'Layers',
    path: '/tools/box-shadow',
    tags: ['css', 'shadow', 'design', 'ui'],
    isNew: true,
  },
  {
    id: 'gradient-studio',
    name: 'Gradient Studio',
    description: 'Build complex linear and radial gradients',
    category: 'image',
    icon: 'Palette',
    path: '/tools/gradient-studio',
    tags: ['css', 'gradient', 'design', 'ui'],
    isNew: true,
  },
  {
    id: 'md-table-generator',
    name: 'Markdown Table Generator',
    description: 'Visually build Markdown tables',
    category: 'text',
    icon: 'Table',
    path: '/tools/md-table-generator',
    tags: ['markdown', 'table', 'documentation', 'generator'],
    isNew: true,
  },
  {
    id: 'cron-tester',
    name: 'Cron Expression Tester',
    description: 'Test and predict cron execution dates',
    category: 'developer',
    icon: 'Clock',
    path: '/tools/cron-tester',
    tags: ['cron', 'tester', 'schedule', 'predict'],
    isNew: true,
  },
  {
    id: 'json-schema',
    name: 'JSON Schema Generator',
    description: 'Generate JSON Schema from JSON data',
    category: 'developer',
    icon: 'Database',
    path: '/tools/json-schema',
    tags: ['json', 'schema', 'api', 'generate'],
    isNew: true,
  },
  {
    id: 'temperature-converter',
    name: 'Temperature Converter',
    description: 'Convert between Celsius, Fahrenheit, Kelvin',
    category: 'converter',
    icon: 'Thermometer',
    path: '/tools/temperature-converter',
    tags: ['temperature', 'celsius', 'fahrenheit', 'convert'],
    isNew: true,
  },
  {
    id: 'json-viewer',
    name: 'JSON Viewer',
    description: 'Interactive collapsible JSON tree viewer',
    category: 'developer',
    icon: 'FileJson',
    path: '/tools/json-viewer',
    tags: ['json', 'tree', 'viewer', 'visualize'],
    isNew: true,
  },
  {
    id: 'text-statistics',
    name: 'Text Statistics',
    description: 'Detailed analysis of text structure',
    category: 'text',
    icon: 'BarChart3',
    path: '/tools/text-statistics',
    tags: ['text', 'stats', 'analysis', 'insights'],
    isNew: true,
  },
  {
    id: 'json-ts',
    name: 'JSON to TypeScript',
    description: 'Generate TS interfaces from JSON',
    category: 'developer',
    icon: 'Code2',
    path: '/tools/json-ts',
    tags: ['json', 'typescript', 'interface', 'generate'],
    isNew: true,
  },
  {
    id: 'glassmorphism',
    name: 'Glassmorphism Studio',
    description: 'Generate CSS frosted glass effects',
    category: 'image',
    icon: 'Layers',
    path: '/tools/glassmorphism',
    tags: ['css', 'glass', 'ui', 'design'],
    isNew: true,
  },
  {
    id: 'svg-jsx',
    name: 'SVG to JSX',
    description: 'Convert SVG to React components',
    category: 'developer',
    icon: 'Code2',
    path: '/tools/svg-jsx',
    tags: ['svg', 'jsx', 'react', 'convert'],
    isNew: true,
  },
  {
    id: 'color-blindness',
    name: 'Color Blindness Simulator',
    description: 'Test UI accessibility for color vision',
    category: 'image',
    icon: 'Eye',
    path: '/tools/color-blindness',
    tags: ['accessibility', 'color', 'vision', 'test'],
    isNew: true,
  },
  {
    id: 'ipv4-address-converter',
    name: 'IPv4 Address Converter',
    description: 'Convert IP to Integer, Binary, Hex',
    category: 'converter',
    icon: 'Network',
    path: '/tools/ipv4-address-converter',
    tags: ['ip', 'ipv4', 'binary', 'hex', 'convert'],
    isNew: true,
  },
  {
    id: 'toml-yaml',
    name: 'TOML ↔ YAML',
    description: 'Convert between TOML and YAML formats',
    category: 'developer',
    icon: 'FileCode',
    path: '/tools/toml-yaml',
    tags: ['toml', 'yaml', 'convert', 'config'],
    isNew: true,
  },
  {
    id: 'yaml-viewer',
    name: 'YAML Viewer & Formatter',
    description: 'Beautify and sort YAML data',
    category: 'developer',
    icon: 'Eye',
    path: '/tools/yaml-viewer',
    tags: ['yaml', 'format', 'beautify', 'viewer'],
    isNew: true,
  },
  {
    id: 'git-memo',
    name: 'Git Cheat Sheet',
    description: 'Commonly used Git commands reference',
    category: 'developer',
    icon: 'GitBranch',
    path: '/tools/git-memo',
    tags: ['git', 'cheat', 'sheet', 'reference'],
    isNew: true,
  },
  {
    id: 'regex-memo',
    name: 'Regex Cheat Sheet',
    description: 'Regular expression syntax reference',
    category: 'developer',
    icon: 'Regex',
    path: '/tools/regex-memo',
    tags: ['regex', 'cheat', 'sheet', 'reference'],
    isNew: true,
  },
  {
    id: 'email-normalizer',
    name: 'Email Normalizer',
    description: 'Clean and normalize email addresses',
    category: 'developer',
    icon: 'Mail',
    path: '/tools/email-normalizer',
    tags: ['email', 'clean', 'normalize', 'gmail'],
    isNew: true,
  },
  {
    id: 'eta-calculator',
    name: 'ETA Calculator',
    description: 'Calculate estimated time of arrival',
    category: 'math',
    icon: 'Clock',
    path: '/tools/eta-calculator',
    tags: ['eta', 'time', 'progress', 'calculate'],
    isNew: true,
  },
  {
    id: 'math-evaluator',
    name: 'Math Evaluator',
    description: 'Evaluate complex math expressions',
    category: 'math',
    icon: 'Sigma',
    path: '/tools/math-evaluator',
    tags: ['math', 'eval', 'expression', 'scientific'],
    isNew: true,
  },
  {
    id: 'string-obfuscator',
    name: 'String Obfuscator',
    description: 'Mask sensitive parts of a string',
    category: 'security',
    icon: 'ShieldEllipsis',
    path: '/tools/string-obfuscator',
    tags: ['mask', 'obfuscate', 'security', 'privacy'],
    isNew: true,
  },
  {
    id: 'text-unicode',
    name: 'Text to Unicode',
    description: 'Convert text to Unicode escape sequences',
    category: 'converter',
    icon: 'Code',
    path: '/tools/text-unicode',
    tags: ['unicode', 'hex', 'escape', 'convert'],
    isNew: true,
  },
  {
    id: 'wifi-qr',
    name: 'WiFi QR Generator',
    description: 'Create QR codes for WiFi networks',
    category: 'generator',
    icon: 'Wifi',
    path: '/tools/wifi-qr',
    tags: ['wifi', 'qr', 'network', 'connect'],
    isNew: true,
  },
  {
    id: 'json-minify',
    name: 'JSON Minifier',
    description: 'Compress JSON by removing whitespace',
    category: 'developer',
    icon: 'Minimize2',
    path: '/tools/json-minify',
    tags: ['json', 'minify', 'compress', 'optimize'],
    isNew: true,
  },
  {
    id: 'text-binary',
    name: 'Text ↔ Binary',
    description: 'Convert text to binary and vice versa',
    category: 'converter',
    icon: 'Binary',
    path: '/tools/text-binary',
    tags: ['text', 'binary', 'convert', 'encode'],
    isNew: true,
  },
  {
    id: 'safelink-decoder',
    name: 'Safelink Decoder',
    description: 'Decode Outlook / Office 365 safelinks',
    category: 'security',
    icon: 'Unlock',
    path: '/tools/safelink-decoder',
    tags: ['safelink', 'outlook', 'decode', 'security'],
    isNew: true,
  },
  {
    id: 'svg-placeholder',
    name: 'SVG Placeholder',
    description: 'Generate custom SVG placeholder images',
    category: 'image',
    icon: 'Image',
    path: '/tools/svg-placeholder',
    tags: ['svg', 'placeholder', 'image', 'design'],
    isNew: true,
  },
  {
    id: 'hmac-generator',
    name: 'HMAC Generator',
    description: 'Generate message authentication codes',
    category: 'security',
    icon: 'Fingerprint',
    path: '/tools/hmac-generator',
    tags: ['hmac', 'security', 'auth', 'hash'],
    isNew: true,
  },
  {
    id: 'otp-generator',
    name: 'OTP Generator',
    description: 'Generate 2FA TOTP authentication codes',
    category: 'security',
    icon: 'Clock',
    path: '/tools/otp-generator',
    tags: ['otp', 'totp', '2fa', 'security'],
    isNew: true,
  },
  {
    id: 'bip39',
    name: 'BIP39 Generator',
    description: 'Generate secure mnemonic seed phrases',
    category: 'security',
    icon: 'Coins',
    path: '/tools/bip39',
    tags: ['mnemonic', 'seed', 'crypto', 'bitcoin'],
    isNew: true,
  },
  {
    id: 'device-info',
    name: 'Device Information',
    description: 'View hardware and browser details',
    category: 'developer',
    icon: 'Monitor',
    path: '/tools/device-info',
    tags: ['device', 'browser', 'hardware', 'specs'],
    isNew: true,
  },
  {
    id: 'keycode-info',
    name: 'Keycode Info',
    description: 'Find keyboard event keycodes and info',
    category: 'developer',
    icon: 'Keyboard',
    path: '/tools/keycode-info',
    tags: ['keycode', 'keyboard', 'event', 'js'],
    isNew: true,
  },
  {
    id: 'meta-tag-generator',
    name: 'Meta Tag Generator',
    description: 'Generate SEO and social media meta tags',
    category: 'developer',
    icon: 'Share2',
    path: '/tools/meta-tag-generator',
    tags: ['seo', 'meta', 'og', 'twitter', 'social'],
    isNew: true,
  },
  {
    id: 'json-toml',
    name: 'JSON ↔ TOML',
    description: 'Convert between JSON and TOML formats',
    category: 'developer',
    icon: 'FileTerminal',
    path: '/tools/json-toml',
    tags: ['json', 'toml', 'convert', 'config'],
    isNew: true,
  },
  {
    id: 'json-xml',
    name: 'JSON ↔ XML',
    description: 'Convert between JSON and XML formats',
    category: 'developer',
    icon: 'Code',
    path: '/tools/json-xml',
    tags: ['json', 'xml', 'convert', 'data'],
    isNew: true,
  },
  {
    id: 'xml-formatter',
    name: 'XML Formatter',
    description: 'Format and beautify XML data',
    category: 'developer',
    icon: 'Braces',
    path: '/tools/xml-formatter',
    tags: ['xml', 'format', 'beautify', 'pretty'],
    isNew: true,
  },
  {
    id: 'ulid-generator',
    name: 'ULID Generator',
    description: 'Generate sortable unique identifiers',
    category: 'generator',
    icon: 'ArrowDown01',
    path: '/tools/ulid-generator',
    tags: ['ulid', 'id', 'unique', 'sortable'],
    isNew: true,
  },
  {
    id: 'integer-base-converter',
    name: 'Integer Base Converter',
    description: 'Convert between Decimal, Hex, Binary, Octal',
    category: 'converter',
    icon: 'Binary',
    path: '/tools/integer-base-converter',
    tags: ['binary', 'hex', 'decimal', 'convert'],
    isNew: true,
  },
  {
    id: 'roman-numeral-converter',
    name: 'Roman Numeral Converter',
    description: 'Convert Arabic numbers to Roman numerals',
    category: 'converter',
    icon: 'History',
    path: '/tools/roman-numeral-converter',
    tags: ['roman', 'numeral', 'math', 'convert'],
    isNew: true,
  },
  {
    id: 'json-diff',
    name: 'JSON Diff',
    description: 'Compare and find differences in JSON',
    category: 'developer',
    icon: 'Braces',
    path: '/tools/json-diff',
    tags: ['json', 'diff', 'compare', 'structural'],
    isNew: true,
  },
  {
    id: 'token-generator',
    name: 'Secure Token Generator',
    description: 'Generate secure random API tokens',
    category: 'generator',
    icon: 'Fingerprint',
    path: '/tools/token-generator',
    tags: ['token', 'secret', 'key', 'generate'],
    isNew: true,
  },
  {
    id: 'rsa-generator',
    name: 'RSA Key Generator',
    description: 'Generate RSA public and private keys',
    category: 'security',
    icon: 'Key',
    path: '/tools/rsa-generator',
    tags: ['rsa', 'key', 'generator', 'security'],
    isNew: true,
  },
  {
    id: 'password-strength',
    name: 'Password Strength',
    description: 'Analyze password security and crack time',
    category: 'security',
    icon: 'ShieldCheck',
    path: '/tools/password-strength',
    tags: ['password', 'strength', 'security', 'analyze'],
    isNew: true,
  },
  {
    id: 'base64-file',
    name: 'Base64 File Converter',
    description: 'Convert images and files to Base64 strings',
    category: 'converter',
    icon: 'FileUp',
    path: '/tools/base64-file',
    tags: ['base64', 'file', 'image', 'convert'],
    isNew: true,
  },
  {
    id: 'http-status-codes',
    name: 'HTTP Status Codes',
    description: 'Complete reference for HTTP response codes',
    category: 'developer',
    icon: 'BookOpen',
    path: '/tools/http-status-codes',
    tags: ['http', 'status', 'code', 'reference'],
    isNew: true,
  },
  {
    id: 'json-csv',
    name: 'JSON ↔ CSV',
    description: 'Convert between JSON arrays and CSV',
    category: 'developer',
    icon: 'FileSpreadsheet',
    path: '/tools/json-csv',
    tags: ['json', 'csv', 'convert', 'spreadsheet'],
    isNew: true,
  },
  {
    id: 'url-parser',
    name: 'URL Parser',
    description: 'Break down complex URLs into parts',
    category: 'developer',
    icon: 'Link',
    path: '/tools/url-parser',
    tags: ['url', 'parse', 'query', 'params'],
    isNew: true,
  },
  {
    id: 'markdown-html',
    name: 'Markdown ↔ HTML',
    description: 'Convert and preview Markdown and HTML',
    category: 'text',
    icon: 'FileText',
    path: '/tools/markdown-html',
    tags: ['markdown', 'html', 'convert', 'preview'],
    isNew: true,
  },
  {
    id: 'basic-auth',
    name: 'Basic Auth Generator',
    description: 'Generate HTTP Basic Auth headers',
    category: 'security',
    icon: 'Lock',
    path: '/tools/basic-auth',
    tags: ['auth', 'basic', 'header', 'security'],
    isNew: true,
  },
  {
    id: 'aes-encryption',
    name: 'AES Encryption',
    description: 'Encrypt and decrypt text with AES',
    category: 'security',
    icon: 'Lock',
    path: '/tools/aes-encryption',
    tags: ['aes', 'encryption', 'decryption', 'security'],
    isNew: true,
  },
  {
    id: 'bcrypt',
    name: 'Bcrypt Hash/Verify',
    description: 'Hash and verify passwords with Bcrypt',
    category: 'security',
    icon: 'ShieldCheck',
    path: '/tools/bcrypt',
    tags: ['bcrypt', 'password', 'hash', 'security'],
    isNew: true,
  },
  {
    id: 'regex-tester',
    name: 'Regex Tester',
    description: 'Test and debug regular expressions',
    category: 'developer',
    icon: 'Regex',
    path: '/tools/regex-tester',
    tags: ['regex', 'test', 'debug', 'developer'],
    isNew: true,
  },
  {
    id: 'ascii-text-drawer',
    name: 'ASCII Text Drawer',
    description: 'Generate ASCII art banners and text',
    category: 'generator',
    icon: 'Layout',
    path: '/tools/ascii-text-drawer',
    tags: ['ascii', 'art', 'banner', 'generate'],
    isNew: true,
  },
  {
    id: 'hash-text',
    name: 'Hash Text',
    description: 'Generate MD5, SHA1, SHA256 hashes',
    category: 'security',
    icon: 'Fingerprint',
    path: '/tools/hash-text',
    tags: ['hash', 'md5', 'sha256', 'security'],
    isNew: true,
  },
  {
    id: 'crontab-generator',
    name: 'Crontab Generator',
    description: 'Create and understand cron expressions',
    category: 'developer',
    icon: 'Clock',
    path: '/tools/crontab-generator',
    tags: ['cron', 'crontab', 'schedule', 'linux'],
    isNew: true,
  },
  {
    id: 'docker-compose-converter',
    name: 'Docker Run to Compose',
    description: 'Convert docker run to docker-compose.yml',
    category: 'developer',
    icon: 'Box',
    path: '/tools/docker-compose-converter',
    tags: ['docker', 'compose', 'devops', 'convert'],
    isNew: true,
  },
  {
    id: 'list-converter',
    name: 'List Converter',
    description: 'Sort, deduplicate, and clean up text lists',
    category: 'text',
    icon: 'ListOrdered',
    path: '/tools/list-converter',
    tags: ['list', 'sort', 'unique', 'clean'],
    isNew: true,
  },
  {
    id: 'slugify',
    name: 'Slugify String',
    description: 'Convert text to URL-friendly slugs',
    category: 'text',
    icon: 'Link2',
    path: '/tools/slugify',
    tags: ['slug', 'url', 'seo', 'convert'],
    isNew: true,
  },
  {
    id: 'subnet-calculator',
    name: 'Subnet Calculator',
    description: 'Calculate IPv4 subnets and CIDR masks',
    category: 'developer',
    icon: 'Network',
    path: '/tools/subnet-calculator',
    tags: ['ip', 'subnet', 'network', 'cidr'],
    isNew: true,
  },
  {
    id: 'user-agent-parser',
    name: 'User Agent Parser',
    description: 'Decode browser user agent strings',
    category: 'developer',
    icon: 'Search',
    path: '/tools/user-agent-parser',
    tags: ['ua', 'useragent', 'browser', 'device'],
    isNew: true,
  },
  {
    id: 'sql-prettify',
    name: 'SQL Prettify',
    description: 'Format and beautify your SQL queries',
    category: 'developer',
    icon: 'Database',
    path: '/tools/sql-prettify',
    tags: ['sql', 'format', 'beautify', 'db'],
    isNew: true,
  },
  {
    id: 'chmod-calculator',
    name: 'Chmod Calculator',
    description: 'Calculate Linux file permissions',
    category: 'developer',
    icon: 'Shield',
    path: '/tools/chmod-calculator',
    tags: ['chmod', 'linux', 'permission', 'security'],
    isNew: true,
  },
  {
    id: 'json-yaml',
    name: 'JSON ↔ YAML',
    description: 'Convert data between JSON and YAML formats',
    category: 'developer',
    icon: 'Braces',
    path: '/tools/json-yaml',
    tags: ['json', 'yaml', 'convert'],
    isNew: true,
  },
  {
    id: 'jwt-parser',
    name: 'JWT Parser',
    description: 'Decode and analyze JSON Web Tokens',
    category: 'developer',
    icon: 'Fingerprint',
    path: '/tools/jwt-parser',
    tags: ['jwt', 'json', 'token', 'decode'],
    isNew: true,
  },
  {
    id: 'html-entities',
    name: 'HTML Entities',
    description: 'Encode and decode HTML entities',
    category: 'developer',
    icon: 'Code',
    path: '/tools/html-entities',
    tags: ['html', 'entities', 'encode', 'decode'],
    isNew: true,
  },
  {
    id: 'lorem-ipsum',
    name: 'Lorem Ipsum',
    description: 'Generate placeholder text for designs',
    category: 'generator',
    icon: 'FileText',
    path: '/tools/lorem-ipsum',
    tags: ['lorem', 'ipsum', 'text', 'generate'],
    isNew: true,
  },
  {
    id: 'json-formatter',
    name: 'JSON Formatter',
    description: 'Format and beautify JSON data',
    category: 'developer',
    icon: 'Braces',
    path: '/tools/json-formatter',
    tags: ['json', 'format', 'beautify'],
  },
  {
    id: 'base64-encoder',
    name: 'Base64 Encoder/Decoder',
    description: 'Encode and decode Base64 strings',
    category: 'developer',
    icon: 'Lock',
    path: '/tools/base64-encoder',
    tags: ['base64', 'encode', 'decode'],
  },
  {
    id: 'url-encoder',
    name: 'URL Encoder/Decoder',
    description: 'Encode and decode URL strings',
    category: 'developer',
    icon: 'Link',
    path: '/tools/url-encoder',
    tags: ['url', 'encode', 'decode'],
  },
  
  // Text Tools
  {
    id: 'word-counter',
    name: 'Word Counter',
    description: 'Count words, characters, and lines',
    category: 'text',
    icon: 'Hash',
    path: '/tools/word-counter',
    tags: ['text', 'count', 'words'],
  },
  {
    id: 'case-converter',
    name: 'Case Converter',
    description: 'Convert text between different cases',
    category: 'text',
    icon: 'Type',
    path: '/tools/case-converter',
    tags: ['text', 'case', 'convert'],
  },
  {
    id: 'text-diff',
    name: 'Text Diff',
    description: 'Compare two texts and find differences',
    category: 'text',
    icon: 'Diff',
    path: '/tools/text-diff',
    tags: ['text', 'diff', 'compare'],
  },
  
  // Converters
  {
    id: 'timestamp-converter',
    name: 'Timestamp Converter',
    description: 'Convert Unix timestamps to readable dates',
    category: 'converter',
    icon: 'Clock',
    path: '/tools/timestamp-converter',
    tags: ['timestamp', 'date', 'convert'],
  },
  {
    id: 'unit-converter',
    name: 'Unit Converter',
    description: 'Convert between different units',
    category: 'converter',
    icon: 'Ruler',
    path: '/tools/unit-converter',
    tags: ['unit', 'convert', 'measurement'],
  },
  {
    id: 'color-converter',
    name: 'Color Converter',
    description: 'Convert between color formats',
    category: 'color',
    icon: 'Palette',
    path: '/tools/color-converter',
    tags: ['color', 'convert', 'hex', 'rgb'],
  },
  
  // Math
  {
    id: 'calculator',
    name: 'Calculator',
    description: 'Simple and scientific calculator',
    category: 'math',
    icon: 'Calculator',
    path: '/tools/calculator',
    tags: ['math', 'calculator', 'calculate'],
  },
  {
    id: 'percentage-calculator',
    name: 'Percentage Calculator',
    description: 'Calculate percentages easily',
    category: 'math',
    icon: 'Percent',
    path: '/tools/percentage-calculator',
    tags: ['math', 'percentage', 'calculate'],
  },
  
  // Generators
  {
    id: 'password-generator',
    name: 'Password Generator',
    description: 'Generate secure random passwords',
    category: 'security',
    icon: 'Key',
    path: '/tools/password-generator',
    tags: ['password', 'generate', 'security'],
  },
  {
    id: 'uuid-generator',
    name: 'UUID Generator',
    description: 'Generate random UUIDs',
    category: 'generator',
    icon: 'Fingerprint',
    path: '/tools/uuid-generator',
    tags: ['uuid', 'generate', 'random'],
  },
  {
    id: 'qr-generator',
    name: 'QR Code Generator',
    description: 'Generate QR codes from text',
    category: 'generator',
    icon: 'QrCode',
    path: '/tools/qr-generator',
    tags: ['qr', 'generate', 'code'],
    isNew: true,
  },
  {
    id: 'image-resize',
    name: 'Image Resize',
    description: 'Resize images in your browser',
    category: 'image',
    icon: 'Maximize',
    path: '/tools/image-resize',
    tags: ['image', 'resize', 'edit'],
    isNew: true,
  },
];

export function getToolsByCategory(categoryId: string): Tool[] {
  return tools.filter(tool => tool.category === categoryId);
}

export function getToolById(id: string): Tool | undefined {
  return tools.find(tool => tool.id === id);
}

export function searchTools(query: string): Tool[] {
  const lowerQuery = query.toLowerCase();
  return tools.filter(
    tool =>
      tool.name.toLowerCase().includes(lowerQuery) ||
      tool.description.toLowerCase().includes(lowerQuery) ||
      tool.tags?.some(tag => tag.toLowerCase().includes(lowerQuery))
  );
}
