export interface Tool {
  id: string;
  name: string;
  description: string;
  category: string;
  icon: string;
  path: string;
  tags?: string[];
  isNew?: boolean;
}

export interface Category {
  id: string;
  name: string;
  description: string;
  icon: string;
}

export const categories: Category[] = [
  {
    id: 'developer',
    name: 'Developer Tools',
    description: 'Tools for developers and programmers',
    icon: 'Code2',
  },
  {
    id: 'text',
    name: 'Text Tools',
    description: 'Text manipulation and formatting',
    icon: 'FileText',
  },
  {
    id: 'converter',
    name: 'Converters',
    description: 'Convert between different formats',
    icon: 'RefreshCw',
  },
  {
    id: 'math',
    name: 'Math',
    description: 'Calculations and math utilities',
    icon: 'Calculator',
  },
  {
    id: 'image',
    name: 'Image Tools',
    description: 'Image manipulation and processing',
    icon: 'Image',
  },
  {
    id: 'color',
    name: 'Color Tools',
    description: 'Color manipulation and conversion',
    icon: 'Palette',
  },
  {
    id: 'generator',
    name: 'Generators',
    description: 'Generate various content',
    icon: 'Sparkles',
  },
  {
    id: 'security',
    name: 'Security',
    description: 'Security and encryption tools',
    icon: 'ShieldCheck',
  },
];

export const tools: Tool[] = [
  // Developer Tools
  {
    id: 'mime-types',
    name: 'MIME Types',
    description: 'Lookup MIME types and file extensions',
    category: 'developer',
    icon: 'FileCode',
    path: '/tools/mime-types',
    tags: ['mime', 'file', 'type', 'extension'],
    isNew: true,
  },
  {
    id: 'stopwatch',
    name: 'Stopwatch',
    description: 'Millisecond timer with lap tracking',
    category: 'math',
    icon: 'Timer',
    path: '/tools/stopwatch',
    tags: ['timer', 'stopwatch', 'chronometer', 'time'],
    isNew: true,
  },
  {
    id: 'numeronym',
    name: 'Numeronym Generator',
    description: 'Generate abbreviations like a11y, i18n',
    category: 'text',
    icon: 'Hash',
    path: '/tools/numeronym',
    tags: ['numeronym', 'abbreviation', 'a11y', 'i18n'],
    isNew: true,
  },
  {
    id: 'nato-alphabet',
    name: 'Text to NATO',
    description: 'Convert text to NATO phonetic alphabet',
    category: 'text',
    icon: 'Globe',
    path: '/tools/nato-alphabet',
    tags: ['nato', 'phonetic', 'alphabet', 'spell'],
    isNew: true,
  },
  {
    id: 'iban-validator',
    name: 'IBAN Validator',
    description: 'Validate and parse IBAN numbers',
    category: 'converter',
    icon: 'Landmark',
    path: '/tools/iban-validator',
    tags: ['iban', 'bank', 'validate', 'transfer'],
    isNew: true,
  },
  {
    id: 'camera-recorder',
    name: 'Camera Recorder',
    description: 'Record video from camera or screen',
    category: 'image',
    icon: 'Camera',
    path: '/tools/camera-recorder',
    tags: ['video', 'record', 'camera', 'screen'],
    isNew: true,
  },
  {
    id: 'emoji-picker',
    name: 'Emoji Picker',
    description: 'Browse and copy emojis easily',
    category: 'generator',
    icon: 'Smile',
    path: '/tools/emoji-picker',
    tags: ['emoji', 'smile', 'copy', 'social'],
    isNew: true,
  },
  {
    id: 'ipv6-ula',
    name: 'IPv6 ULA Generator',
    description: 'Generate unique local IPv6 prefixes',
    category: 'developer',
    icon: 'Globe',
    path: '/tools/ipv6-ula',
    tags: ['ipv6', 'ula', 'network', 'rfc4193'],
    isNew: true,
  },
  {
    id: 'wysiwyg-editor',
    name: 'WYSIWYG Editor',
    description: 'Visual HTML editor with live source',
    category: 'developer',
    icon: 'FileCode',
    path: '/tools/wysiwyg-editor',
    tags: ['html', 'editor', 'wysiwyg', 'web'],
    isNew: true,
  },
  {
    id: 'phone-parser',
    name: 'Phone Parser',
    description: 'Validate and format phone numbers',
    category: 'text',
    icon: 'Phone',
    path: '/tools/phone-parser',
    tags: ['phone', 'format', 'validate', 'mobile'],
    isNew: true,
  },
  {
    id: 'mac-address',
    name: 'MAC Address Tool',
    description: 'Generate and lookup MAC addresses',
    category: 'developer',
    icon: 'Monitor',
    path: '/tools/mac-address',
    tags: ['mac', 'address', 'oui', 'vendor'],
    isNew: true,
  },
  {
    id: 'port-generator',
    name: 'Random Port Generator',
    description: 'Generate random non-conflicting ports',
    category: 'developer',
    icon: 'Server',
    path: '/tools/port-generator',
    tags: ['port', 'tcp', 'udp', 'network'],
    isNew: true,
  },
  {
    id: 'ip-range-expander',
    name: 'IP Range Expander',
    description: 'Expand CIDR and IP ranges to lists',
    category: 'developer',
    icon: 'Maximize2',
    path: '/tools/ip-range-expander',
    tags: ['ip', 'range', 'cidr', 'expand'],
    isNew: true,
  },
  {
    id: 'wifi-qr',
    name: 'WiFi QR Generator',
    description: 'Create QR codes for WiFi networks',
    category: 'generator',
    icon: 'Wifi',
    path: '/tools/wifi-qr',
    tags: ['wifi', 'qr', 'network', 'connect'],
    isNew: true,
  },
  {
    id: 'json-minify',
    name: 'JSON Minifier',
    description: 'Compress JSON by removing whitespace',
    category: 'developer',
    icon: 'Minimize2',
    path: '/tools/json-minify',
    tags: ['json', 'minify', 'compress', 'optimize'],
    isNew: true,
  },
  {
    id: 'text-binary',
    name: 'Text ↔ Binary',
    description: 'Convert text to binary and vice versa',
    category: 'converter',
    icon: 'Binary',
    path: '/tools/text-binary',
    tags: ['text', 'binary', 'convert', 'encode'],
    isNew: true,
  },
  {
    id: 'safelink-decoder',
    name: 'Safelink Decoder',
    description: 'Decode Outlook / Office 365 safelinks',
    category: 'security',
    icon: 'Unlock',
    path: '/tools/safelink-decoder',
    tags: ['safelink', 'outlook', 'decode', 'security'],
    isNew: true,
  },
  {
    id: 'svg-placeholder',
    name: 'SVG Placeholder',
    description: 'Generate custom SVG placeholder images',
    category: 'image',
    icon: 'Image',
    path: '/tools/svg-placeholder',
    tags: ['svg', 'placeholder', 'image', 'design'],
    isNew: true,
  },
  {
    id: 'hmac-generator',
    name: 'HMAC Generator',
    description: 'Generate message authentication codes',
    category: 'security',
    icon: 'Fingerprint',
    path: '/tools/hmac-generator',
    tags: ['hmac', 'security', 'auth', 'hash'],
    isNew: true,
  },
  {
    id: 'otp-generator',
    name: 'OTP Generator',
    description: 'Generate 2FA TOTP authentication codes',
    category: 'security',
    icon: 'Clock',
    path: '/tools/otp-generator',
    tags: ['otp', 'totp', '2fa', 'security'],
    isNew: true,
  },
  {
    id: 'bip39',
    name: 'BIP39 Generator',
    description: 'Generate secure mnemonic seed phrases',
    category: 'security',
    icon: 'Coins',
    path: '/tools/bip39',
    tags: ['mnemonic', 'seed', 'crypto', 'bitcoin'],
    isNew: true,
  },
  {
    id: 'device-info',
    name: 'Device Information',
    description: 'View hardware and browser details',
    category: 'developer',
    icon: 'Monitor',
    path: '/tools/device-info',
    tags: ['device', 'browser', 'hardware', 'specs'],
    isNew: true,
  },
  {
    id: 'keycode-info',
    name: 'Keycode Info',
    description: 'Find keyboard event keycodes and info',
    category: 'developer',
    icon: 'Keyboard',
    path: '/tools/keycode-info',
    tags: ['keycode', 'keyboard', 'event', 'js'],
    isNew: true,
  },
  {
    id: 'meta-tag-generator',
    name: 'Meta Tag Generator',
    description: 'Generate SEO and social media meta tags',
    category: 'developer',
    icon: 'Share2',
    path: '/tools/meta-tag-generator',
    tags: ['seo', 'meta', 'og', 'twitter', 'social'],
    isNew: true,
  },
  {
    id: 'json-toml',
    name: 'JSON ↔ TOML',
    description: 'Convert between JSON and TOML formats',
    category: 'developer',
    icon: 'FileTerminal',
    path: '/tools/json-toml',
    tags: ['json', 'toml', 'convert', 'config'],
    isNew: true,
  },
  {
    id: 'json-xml',
    name: 'JSON ↔ XML',
    description: 'Convert between JSON and XML formats',
    category: 'developer',
    icon: 'Code',
    path: '/tools/json-xml',
    tags: ['json', 'xml', 'convert', 'data'],
    isNew: true,
  },
  {
    id: 'xml-formatter',
    name: 'XML Formatter',
    description: 'Format and beautify XML data',
    category: 'developer',
    icon: 'Braces',
    path: '/tools/xml-formatter',
    tags: ['xml', 'format', 'beautify', 'pretty'],
    isNew: true,
  },
  {
    id: 'ulid-generator',
    name: 'ULID Generator',
    description: 'Generate sortable unique identifiers',
    category: 'generator',
    icon: 'ArrowDown01',
    path: '/tools/ulid-generator',
    tags: ['ulid', 'id', 'unique', 'sortable'],
    isNew: true,
  },
  {
    id: 'integer-base-converter',
    name: 'Integer Base Converter',
    description: 'Convert between Decimal, Hex, Binary, Octal',
    category: 'converter',
    icon: 'Binary',
    path: '/tools/integer-base-converter',
    tags: ['binary', 'hex', 'decimal', 'convert'],
    isNew: true,
  },
  {
    id: 'roman-numeral-converter',
    name: 'Roman Numeral Converter',
    description: 'Convert Arabic numbers to Roman numerals',
    category: 'converter',
    icon: 'History',
    path: '/tools/roman-numeral-converter',
    tags: ['roman', 'numeral', 'math', 'convert'],
    isNew: true,
  },
  {
    id: 'json-diff',
    name: 'JSON Diff',
    description: 'Compare and find differences in JSON',
    category: 'developer',
    icon: 'Braces',
    path: '/tools/json-diff',
    tags: ['json', 'diff', 'compare', 'structural'],
    isNew: true,
  },
  {
    id: 'token-generator',
    name: 'Secure Token Generator',
    description: 'Generate secure random API tokens',
    category: 'generator',
    icon: 'Fingerprint',
    path: '/tools/token-generator',
    tags: ['token', 'secret', 'key', 'generate'],
    isNew: true,
  },
  {
    id: 'rsa-generator',
    name: 'RSA Key Generator',
    description: 'Generate RSA public and private keys',
    category: 'security',
    icon: 'Key',
    path: '/tools/rsa-generator',
    tags: ['rsa', 'key', 'generator', 'security'],
    isNew: true,
  },
  {
    id: 'password-strength',
    name: 'Password Strength',
    description: 'Analyze password security and crack time',
    category: 'security',
    icon: 'ShieldCheck',
    path: '/tools/password-strength',
    tags: ['password', 'strength', 'security', 'analyze'],
    isNew: true,
  },
  {
    id: 'base64-file',
    name: 'Base64 File Converter',
    description: 'Convert images and files to Base64 strings',
    category: 'converter',
    icon: 'FileUp',
    path: '/tools/base64-file',
    tags: ['base64', 'file', 'image', 'convert'],
    isNew: true,
  },
  {
    id: 'http-status-codes',
    name: 'HTTP Status Codes',
    description: 'Complete reference for HTTP response codes',
    category: 'developer',
    icon: 'BookOpen',
    path: '/tools/http-status-codes',
    tags: ['http', 'status', 'code', 'reference'],
    isNew: true,
  },
  {
    id: 'json-csv',
    name: 'JSON ↔ CSV',
    description: 'Convert between JSON arrays and CSV',
    category: 'developer',
    icon: 'FileSpreadsheet',
    path: '/tools/json-csv',
    tags: ['json', 'csv', 'convert', 'spreadsheet'],
    isNew: true,
  },
  {
    id: 'url-parser',
    name: 'URL Parser',
    description: 'Break down complex URLs into parts',
    category: 'developer',
    icon: 'Link',
    path: '/tools/url-parser',
    tags: ['url', 'parse', 'query', 'params'],
    isNew: true,
  },
  {
    id: 'markdown-html',
    name: 'Markdown ↔ HTML',
    description: 'Convert and preview Markdown and HTML',
    category: 'text',
    icon: 'FileText',
    path: '/tools/markdown-html',
    tags: ['markdown', 'html', 'convert', 'preview'],
    isNew: true,
  },
  {
    id: 'basic-auth',
    name: 'Basic Auth Generator',
    description: 'Generate HTTP Basic Auth headers',
    category: 'security',
    icon: 'Lock',
    path: '/tools/basic-auth',
    tags: ['auth', 'basic', 'header', 'security'],
    isNew: true,
  },
  {
    id: 'aes-encryption',
    name: 'AES Encryption',
    description: 'Encrypt and decrypt text with AES',
    category: 'security',
    icon: 'Lock',
    path: '/tools/aes-encryption',
    tags: ['aes', 'encryption', 'decryption', 'security'],
    isNew: true,
  },
  {
    id: 'bcrypt',
    name: 'Bcrypt Hash/Verify',
    description: 'Hash and verify passwords with Bcrypt',
    category: 'security',
    icon: 'ShieldCheck',
    path: '/tools/bcrypt',
    tags: ['bcrypt', 'password', 'hash', 'security'],
    isNew: true,
  },
  {
    id: 'regex-tester',
    name: 'Regex Tester',
    description: 'Test and debug regular expressions',
    category: 'developer',
    icon: 'Regex',
    path: '/tools/regex-tester',
    tags: ['regex', 'test', 'debug', 'developer'],
    isNew: true,
  },
  {
    id: 'ascii-text-drawer',
    name: 'ASCII Text Drawer',
    description: 'Generate ASCII art banners and text',
    category: 'generator',
    icon: 'Layout',
    path: '/tools/ascii-text-drawer',
    tags: ['ascii', 'art', 'banner', 'generate'],
    isNew: true,
  },
  {
    id: 'hash-text',
    name: 'Hash Text',
    description: 'Generate MD5, SHA1, SHA256 hashes',
    category: 'security',
    icon: 'Fingerprint',
    path: '/tools/hash-text',
    tags: ['hash', 'md5', 'sha256', 'security'],
    isNew: true,
  },
  {
    id: 'crontab-generator',
    name: 'Crontab Generator',
    description: 'Create and understand cron expressions',
    category: 'developer',
    icon: 'Clock',
    path: '/tools/crontab-generator',
    tags: ['cron', 'crontab', 'schedule', 'linux'],
    isNew: true,
  },
  {
    id: 'docker-compose-converter',
    name: 'Docker Run to Compose',
    description: 'Convert docker run to docker-compose.yml',
    category: 'developer',
    icon: 'Box',
    path: '/tools/docker-compose-converter',
    tags: ['docker', 'compose', 'devops', 'convert'],
    isNew: true,
  },
  {
    id: 'list-converter',
    name: 'List Converter',
    description: 'Sort, deduplicate, and clean up text lists',
    category: 'text',
    icon: 'ListOrdered',
    path: '/tools/list-converter',
    tags: ['list', 'sort', 'unique', 'clean'],
    isNew: true,
  },
  {
    id: 'slugify',
    name: 'Slugify String',
    description: 'Convert text to URL-friendly slugs',
    category: 'text',
    icon: 'Link2',
    path: '/tools/slugify',
    tags: ['slug', 'url', 'seo', 'convert'],
    isNew: true,
  },
  {
    id: 'subnet-calculator',
    name: 'Subnet Calculator',
    description: 'Calculate IPv4 subnets and CIDR masks',
    category: 'developer',
    icon: 'Network',
    path: '/tools/subnet-calculator',
    tags: ['ip', 'subnet', 'network', 'cidr'],
    isNew: true,
  },
  {
    id: 'user-agent-parser',
    name: 'User Agent Parser',
    description: 'Decode browser user agent strings',
    category: 'developer',
    icon: 'Search',
    path: '/tools/user-agent-parser',
    tags: ['ua', 'useragent', 'browser', 'device'],
    isNew: true,
  },
  {
    id: 'sql-prettify',
    name: 'SQL Prettify',
    description: 'Format and beautify your SQL queries',
    category: 'developer',
    icon: 'Database',
    path: '/tools/sql-prettify',
    tags: ['sql', 'format', 'beautify', 'db'],
    isNew: true,
  },
  {
    id: 'chmod-calculator',
    name: 'Chmod Calculator',
    description: 'Calculate Linux file permissions',
    category: 'developer',
    icon: 'Shield',
    path: '/tools/chmod-calculator',
    tags: ['chmod', 'linux', 'permission', 'security'],
    isNew: true,
  },
  {
    id: 'json-yaml',
    name: 'JSON ↔ YAML',
    description: 'Convert data between JSON and YAML formats',
    category: 'developer',
    icon: 'Braces',
    path: '/tools/json-yaml',
    tags: ['json', 'yaml', 'convert'],
    isNew: true,
  },
  {
    id: 'jwt-parser',
    name: 'JWT Parser',
    description: 'Decode and analyze JSON Web Tokens',
    category: 'developer',
    icon: 'Fingerprint',
    path: '/tools/jwt-parser',
    tags: ['jwt', 'json', 'token', 'decode'],
    isNew: true,
  },
  {
    id: 'html-entities',
    name: 'HTML Entities',
    description: 'Encode and decode HTML entities',
    category: 'developer',
    icon: 'Code',
    path: '/tools/html-entities',
    tags: ['html', 'entities', 'encode', 'decode'],
    isNew: true,
  },
  {
    id: 'lorem-ipsum',
    name: 'Lorem Ipsum',
    description: 'Generate placeholder text for designs',
    category: 'generator',
    icon: 'FileText',
    path: '/tools/lorem-ipsum',
    tags: ['lorem', 'ipsum', 'text', 'generate'],
    isNew: true,
  },
  {
    id: 'json-formatter',
    name: 'JSON Formatter',
    description: 'Format and beautify JSON data',
    category: 'developer',
    icon: 'Braces',
    path: '/tools/json-formatter',
    tags: ['json', 'format', 'beautify'],
  },
  {
    id: 'base64-encoder',
    name: 'Base64 Encoder/Decoder',
    description: 'Encode and decode Base64 strings',
    category: 'developer',
    icon: 'Lock',
    path: '/tools/base64-encoder',
    tags: ['base64', 'encode', 'decode'],
  },
  {
    id: 'url-encoder',
    name: 'URL Encoder/Decoder',
    description: 'Encode and decode URL strings',
    category: 'developer',
    icon: 'Link',
    path: '/tools/url-encoder',
    tags: ['url', 'encode', 'decode'],
  },
  
  // Text Tools
  {
    id: 'word-counter',
    name: 'Word Counter',
    description: 'Count words, characters, and lines',
    category: 'text',
    icon: 'Hash',
    path: '/tools/word-counter',
    tags: ['text', 'count', 'words'],
  },
  {
    id: 'case-converter',
    name: 'Case Converter',
    description: 'Convert text between different cases',
    category: 'text',
    icon: 'Type',
    path: '/tools/case-converter',
    tags: ['text', 'case', 'convert'],
  },
  {
    id: 'text-diff',
    name: 'Text Diff',
    description: 'Compare two texts and find differences',
    category: 'text',
    icon: 'Diff',
    path: '/tools/text-diff',
    tags: ['text', 'diff', 'compare'],
  },
  
  // Converters
  {
    id: 'timestamp-converter',
    name: 'Timestamp Converter',
    description: 'Convert Unix timestamps to readable dates',
    category: 'converter',
    icon: 'Clock',
    path: '/tools/timestamp-converter',
    tags: ['timestamp', 'date', 'convert'],
  },
  {
    id: 'unit-converter',
    name: 'Unit Converter',
    description: 'Convert between different units',
    category: 'converter',
    icon: 'Ruler',
    path: '/tools/unit-converter',
    tags: ['unit', 'convert', 'measurement'],
  },
  {
    id: 'color-converter',
    name: 'Color Converter',
    description: 'Convert between color formats',
    category: 'color',
    icon: 'Palette',
    path: '/tools/color-converter',
    tags: ['color', 'convert', 'hex', 'rgb'],
  },
  
  // Math
  {
    id: 'calculator',
    name: 'Calculator',
    description: 'Simple and scientific calculator',
    category: 'math',
    icon: 'Calculator',
    path: '/tools/calculator',
    tags: ['math', 'calculator', 'calculate'],
  },
  {
    id: 'percentage-calculator',
    name: 'Percentage Calculator',
    description: 'Calculate percentages easily',
    category: 'math',
    icon: 'Percent',
    path: '/tools/percentage-calculator',
    tags: ['math', 'percentage', 'calculate'],
  },
  
  // Generators
  {
    id: 'password-generator',
    name: 'Password Generator',
    description: 'Generate secure random passwords',
    category: 'security',
    icon: 'Key',
    path: '/tools/password-generator',
    tags: ['password', 'generate', 'security'],
  },
  {
    id: 'uuid-generator',
    name: 'UUID Generator',
    description: 'Generate random UUIDs',
    category: 'generator',
    icon: 'Fingerprint',
    path: '/tools/uuid-generator',
    tags: ['uuid', 'generate', 'random'],
  },
  {
    id: 'qr-generator',
    name: 'QR Code Generator',
    description: 'Generate QR codes from text',
    category: 'generator',
    icon: 'QrCode',
    path: '/tools/qr-generator',
    tags: ['qr', 'generate', 'code'],
    isNew: true,
  },
  {
    id: 'image-resize',
    name: 'Image Resize',
    description: 'Resize images in your browser',
    category: 'image',
    icon: 'Maximize',
    path: '/tools/image-resize',
    tags: ['image', 'resize', 'edit'],
    isNew: true,
  },
];

export function getToolsByCategory(categoryId: string): Tool[] {
  return tools.filter(tool => tool.category === categoryId);
}

export function getToolById(id: string): Tool | undefined {
  return tools.find(tool => tool.id === id);
}

export function searchTools(query: string): Tool[] {
  const lowerQuery = query.toLowerCase();
  return tools.filter(
    tool =>
      tool.name.toLowerCase().includes(lowerQuery) ||
      tool.description.toLowerCase().includes(lowerQuery) ||
      tool.tags?.some(tag => tag.toLowerCase().includes(lowerQuery))
  );
}
