declare module 'composerize';
declare module 'unicode-emoji-json';
declare module 'json-diff';
declare module 'figlet/importable-fonts/*.js';
declare module 'generate-json-schema';
declare module 'cron-parser';
declare module 'colorthief';
declare module 'text-readability';
declare module 'curlconverter';
